### ISSUE TITLE
Locate person by Region

### ISSUE THREAD

**Issue by FireRadical22** [AY2223S2-CS2103T-W12-3/tp#11]
Implement Locate Person By Region feature

Format: ```find REGION [PERSON_INDEX]```

Required information:
- Region person is residing in
- Region specified should be a valid region 

Examples:
- find Central  
- find NorthEast 3

**Comment by bokung** [comment]
Currently it displays the region directly on the person card. I think shouldn't need to find where a person is residing using a command now?
