### ISSUE TITLE
[PE-D][Tester A] One to one meeting restriction

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W12-3/tp#120]
Currently, faid allows only 1-on-1 meeting with clients since it is a financial advisor app. That is great since meeting with multiple people does not make sense. However, in that case, why does the meetingUpdate need both the client Index and meeting index? Why not just update the meeting Index and then the client index updates automatically? 

I think it will be great to simply just specify the meetingIndex instead. There are a few bugs related due to this as seen in other issues I have created

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: ARPspoofing/ped#11

**Comment by FireRadical22** [comment]
Duplicate issue
