### ISSUE TITLE
[PE-D][Tester D] Exiting and reopening app results in glitched meetings

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W12-3/tp#150]
Steps to reproduce:
Add a meeting, exit via CLI and open the app again.
![image.png](https://raw.githubusercontent.com/sumhungyee/ped/main/files/759659e3-d747-49cf-b9d0-be9f7e096699.png)

![image.png](https://raw.githubusercontent.com/sumhungyee/ped/main/files/a2c71cbe-879a-4dd9-8a66-c17d30bceb79.png)

Suggestions:
Not sure if this problem comes from the conversion of objects into strings. maybe just save the string?

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: sumhungyee/ped#15

**Comment by bokung** [comment]
Meeting saving and loading is fixed
